import "./globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"


export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      
      
      
      <body className={inter.className}>{children}</body>
     
      
    </html>
  )
}







